# permissions for end users to view jobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: job-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubesync
    app.kubernetes.io/part-of: kubesync
    app.kubernetes.io/managed-by: kustomize
  name: job-viewer-role
rules:
- apiGroups:
  - redrock.team
  resources:
  - mirrorjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redrock.team
  resources:
  - mirrorjobs/status
  verbs:
  - get
