# permissions for end users to view managers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: manager-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubesync
    app.kubernetes.io/part-of: kubesync
    app.kubernetes.io/managed-by: kustomize
  name: manager-viewer-role
rules:
- apiGroups:
  - mirror.redrock.team
  resources:
  - managers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mirror.redrock.team
  resources:
  - managers/status
  verbs:
  - get
