---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - redrock.team
  resources:
  - mirrorjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redrock.team
  resources:
  - mirrorjobs/finalizers
  verbs:
  - update
- apiGroups:
  - redrock.team
  resources:
  - mirrorjobs/status
  verbs:
  - get
  - patch
  - update
