apiVersion: mirror.redrock.team/v1beta1
kind: Manager
metadata:
  labels:
    app.kubernetes.io/name: manager
    app.kubernetes.io/instance: manager-sample
    app.kubernetes.io/part-of: kubesync
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubesync
  name: manager-sample
spec:
  image: ghcr.io/cquptmirror/manager:dev  # Required
  imagePullPolicy: Always
#  imagePullSecrets:
#  nodeName:
#  affinity:
#  tolerations:
#  cpuLimit:
#  memLimit:
#  ingress:
#    ingressClass:  # Ingress class used to deploy the api service
#    TLSSecret:  # TLS secret used to deploy the api service
#    host:  # Domain used to deploy the api service
#    annotations:  # Addition ingress annotations used to deploy the api service, split by ';'
