apiVersion: mirror.redrock.team/v1beta1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: job
    app.kubernetes.io/instance: job-sample
    app.kubernetes.io/part-of: kubesync
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubesync
  name: job-sample
spec:
  config:
    alias: tlpretest  # Alias of this mirror, optional
    desc: "Test job"  # Description of this mirror, optional
#    url:  # Specify url for front to redirect, optional
#    helpUrl:  # Specify helpUrl for manager to return, optional
#    type:  # Type of this mirror, mirror / proxy, if value is proxy, job will not create and just return info in api, optional
    upstream: "rsync://tug.org/tlpretest/"  # The upstream url of this job, required
    provider: rsync  # The sync provider of this job, default rsync, optional
#    mirrorPath:  # Specify a dir to store mirror files, pvc will also mount to this path, default /data/{name}, optional
#    command:  # The sync command of this job, optional
#    concurrent:  # The sync concurrent of this job, default 3, optional
#    interval:  # The sync interval (minutes) of this job, default 1440, optional
#    retry:  # The retry num of this job, default 2, optional
#    timeout:  # The sync timeout (minutes) of this job, default 0, optional
#    failOnMatch:  # The regexp to judge whether command job failed, optional
#    IPv6Only:  # IPv6 only, optional
#    IPv4Only:  # IPv4 only, optional
#    excludeFile:  # Exclude files in rsync job, optional
#    rsyncOptions:  # Extra rsync options, optional
#    stage1Profile:  # Two stage rsync stage 1 profile, optional
#    execOnSuccess:  # Success hook, optional
#    execOnFailure:  # Failure hook, optional
#    sizePattern:  # The regexp to get command job size form log, optional
#    additionEnvs:  # The addition environments set to job container
#    debug:  # Whether enable worker debug mode
  deploy:
    image: ghcr.io/cquptmirror/worker:dev  # Default use controller config, optional
    imagePullPolicy: Always  # Optional
#    imagePullSecrets:
#    nodeName:
#    affinity:
#    tolerations:
#    cpuLimit:
#    memLimit:
#    disableFront:  # Disable directory service in this job
#    frontImage:  # Image used to deploy the directory service
#    frontCmd:  # Command used to deploy the directory service
#    disableRsync:  # Disable rsync service in this job
#    rsyncImage:  # Image used to deploy the rsync service
#    rsyncCmd:  # Command used to deploy the rsync service
  volume:
    size: 1Mi  # The size of the job pvc, required
#    storageClass:  # The storage class the job pve to use
#    accessMode:  # Access mode of this pvc
#  ingress:
#    ingressClass:  # Ingress class used to deploy the directory service
#    TLSSecret:  # TLS secret used to deploy the directory service
#    host:  # Domain used to deploy the directory service
#    annotations:  # Addition ingress annotations used to deploy the directory service, split by ';'
