apiVersion: mirror.redrock.team/v1beta1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: job
    app.kubernetes.io/instance: job-sample
    app.kubernetes.io/part-of: kubesync
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubesync
  name: job-sample
spec:
  config:
    alias: tlpretest
    upstream: "rsync://tug.org/tlpretest/"
    provider: rsync
  deploy:
    image: ghcr.io/CQUPTMirror/worker:dev
  volume:
    size: 1Mi
