#!/bin/python3
import os
import requests
from urllib.parse import urljoin


def find(path: str = "/data", ext: list = None, include: str = '', exclude: str = "placeholder") -> list:
    if ext is None:
        ext = [".iso"]
    find_files = []
    for root, dirs, files in os.walk(path):
        files = [f for f in files if not f[0] == '.']
        dirs[:] = [d for d in dirs if not d[0] == '.']
        if (not include or include in root) and exclude not in root:
            find_files.extend([os.path.join(root.removeprefix(path), i) for i in files if os.path.splitext(i)[-1] in ext and include in i and exclude not in i])
    return find_files


if __name__ == "__main__":
    name = os.getenv("NAME")
    if not name:
        print("no name provide")
        exit(1)
    path = os.getenv("FIND_PATH", "/data")
    ext = os.getenv("FIND_EXT", ".iso").split(';')
    include = os.getenv("FIND_INCLUDE", "")
    exclude = os.getenv("FIND_EXCLUDE", "placeholder")
    api = os.getenv("API", "http://manager-sample:3000")
    files = find(path, ext, include, exclude)
    try:
        req = requests.post(urljoin(api, f"/file/{name}"), json={"files": files})
        req.raise_for_status()
        print("update file list succeed")
    except:
        print("failed to update file list: request error")
