apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: kubesync
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: kubesync
    app.kubernetes.io/part-of: kubesync
    app.kubernetes.io/managed-by: kustomize
  name: kubesync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: kubesync
  labels:
    control-plane: controller
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/created-by: kubesync
    app.kubernetes.io/part-of: kubesync
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: controller
      labels:
        control-plane: controller
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
      securityContext:
        runAsNonRoot: true
      containers:
      - name: controller
        image: ghcr.io/CQUPTMirror/kubesync:controller
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: controller
      terminationGracePeriodSeconds: 10
