name: Build and Push Docker Images

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'config/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'config/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        worker: [ anaconda, bandersnatch, entware, git, github-release ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push controller image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.controller
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/cquptmirror/controller:dev
            cquptmirror/controller:dev
      - name: Build and Push manager image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.manager
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/cquptmirror/manager:dev
            cquptmirror/manager:dev
      - name: Build and Push worker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.worker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/cquptmirror/worker:dev
            cquptmirror/worker:dev
      - name: Build and Push ${{ matrix.worker }} worker image
        uses: docker/build-push-action@v5
        with:
          context: docker/worker/${{ matrix.worker }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/cquptmirror/worker:${{ matrix.worker }}
            cquptmirror/worker:${{ matrix.worker }}
